name: hi_market
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  get_it: ^3.1.0
  shared_preferences:
  fluttertoast: ^3.1.3
  solid_bottom_sheet: ^0.1.9
 # path_provider:
  progress_indicators: ^0.1.4
  get: ^3.26.0
  liquid_pull_to_refresh: ^1.1.1
  flutter_launcher_icons: ^0.9.0
  path:
  share: ^0.6.4+3
  youtube_player_flutter: ^8.0.0
  chewie:
  url_launcher: ^5.7.5
  image_picker: ^0.7.4
  flutter_html: ^1.3.0
  google_fonts:
  progress_dialog: ^1.2.1
  open_file: ^3.0.3
  move_to_background: ^0.2.0
  firebase_messaging: ^7.0.3
  flutter_plugin_android_lifecycle: ^2.0.1
  firebase_core: ^0.5.0
  #flutter_cached_pdfview:
  #pdf: ^3.4.2
  badges: ^2.0.1
  fancy_bottom_navigation: ^0.3.3
  flutter_svg:
  lottie: ^1.1.0
  native_pdf_view: ^4.1.0
 # flutter_gifimage: ^1.0.1
  transformer_page_view: ^0.1.6
  #neeko:
 # flutter_vlc_player:
 # better_player: any




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launch_icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ youtube.svg
    - images/addUser.png
    - images/Al_Ahly_SC_logo.png
    - images/backimage.png
    - images/ballimage.png
    - images/baseketball_splash.json
    - images/basket.png
    - images/basketball.jpg
    - images/basketball_load.json
    - images/basketballicon.png
    - images/basketiconlistimage.png
    - images/bell.png
    - images/blackballimage.jpeg
    - images/checkmark.png
    - images/competitionimage.png
    - images/discount.png
    - images/editMatch.png
    - images/email_blocker.png
    - images/email_contact_us.png
    - images/error.svg
    - images/facebook.svg
    - images/gameimage.jpeg
    - images/Group_362.png
    - images/Group_529.svg
    - images/Group_530.svg
    - images/Group_531.svg
    - images/Group_532.svg
    - images/Group_533.svg
    - images/Group_534.svg
    - images/Group_535.svg
    - images/Group_537.svg
    - images/hiclipart.com.png
    - images/images.svg
    - images/instagram.svg
    - images/instgram.png
    - images/launch_icon.png
    - images/liberaryimage.jpeg
    - images/logo.png
    - images/mainpage.png
    - images/Menu.png
    - images/money.png
    - images/mortaga3.png
    - images/nadiimage.png
    - images/paper.svg
    - images/phone_contact_us.png
    - images/Rectangle.png
    - images/Rectangle_731.png
    - images/recycle.png
    - images/retern.png
    - images/saveMatch.png
    - images/search.png
    - images/sideMenuLogo.png
    - images/Smouha_SC_logo.png
    - images/splash.json
    - images/success.png
    - images/twitter.svg
    - images/user.png
    - images/warning.png
    - images/whistle.png
    - images/wightballimage.jpeg
    - images/wightbasketimage.jpeg
    - images/x_button.png
    - images/Youtube.svg
    - images/youtube_image.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: Cairo
    fonts:
      - asset: fonts/Cairo-Black.ttf
      - asset: fonts/Cairo-Bold.ttf
      - asset: fonts/Cairo-ExtraLight.ttf
      - asset: fonts/Cairo-Light.ttf
      - asset: fonts/Cairo-Regular.ttf
      - asset: fonts/Cairo-SemiBold.ttf
        style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
